// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// symmetrize
arma::mat symmetrize(const arma::mat& A);
RcppExport SEXP _ksm_symmetrize(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(symmetrize(A));
    return rcpp_result_gen;
END_RCPP
}
// sumlog
double sumlog(const arma::vec& x);
RcppExport SEXP _ksm_sumlog(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sumlog(x));
    return rcpp_result_gen;
END_RCPP
}
// meanlog
double meanlog(const arma::vec& x);
RcppExport SEXP _ksm_meanlog(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(meanlog(x));
    return rcpp_result_gen;
END_RCPP
}
// sumsignedlog
double sumsignedlog(const arma::vec& x, Rcpp::LogicalVector sgn);
RcppExport SEXP _ksm_sumsignedlog(SEXP xSEXP, SEXP sgnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type sgn(sgnSEXP);
    rcpp_result_gen = Rcpp::wrap(sumsignedlog(x, sgn));
    return rcpp_result_gen;
END_RCPP
}
// rotation2d
arma::mat rotation2d(double par);
RcppExport SEXP _ksm_rotation2d(SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(rotation2d(par));
    return rcpp_result_gen;
END_RCPP
}
// rotation3d
arma::mat rotation3d(arma::vec par);
RcppExport SEXP _ksm_rotation3d(SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(rotation3d(par));
    return rcpp_result_gen;
END_RCPP
}
// rotation_scaling
arma::mat rotation_scaling(arma::vec ang, arma::vec scale);
RcppExport SEXP _ksm_rotation_scaling(SEXP angSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type ang(angSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(rotation_scaling(ang, scale));
    return rcpp_result_gen;
END_RCPP
}
// mgamma
arma::vec mgamma(const arma::vec& x, int p, bool log);
RcppExport SEXP _ksm_mgamma(SEXP xSEXP, SEXP pSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(mgamma(x, p, log));
    return rcpp_result_gen;
END_RCPP
}
// lmgamma
double lmgamma(double x, arma::uword p);
RcppExport SEXP _ksm_lmgamma(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(lmgamma(x, p));
    return rcpp_result_gen;
END_RCPP
}
// dWishart
arma::vec dWishart(const arma::cube& x, double df, const arma::mat& S, bool log);
RcppExport SEXP _ksm_dWishart(SEXP xSEXP, SEXP dfSEXP, SEXP SSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dWishart(x, df, S, log));
    return rcpp_result_gen;
END_RCPP
}
// dinvWishart
arma::vec dinvWishart(const arma::cube& x, double df, const arma::mat& S, bool log);
RcppExport SEXP _ksm_dinvWishart(SEXP xSEXP, SEXP dfSEXP, SEXP SSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dinvWishart(x, df, S, log));
    return rcpp_result_gen;
END_RCPP
}
// dWishart_mat
double dWishart_mat(const arma::mat& x, double df, const arma::mat& S, bool log);
RcppExport SEXP _ksm_dWishart_mat(SEXP xSEXP, SEXP dfSEXP, SEXP SSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dWishart_mat(x, df, S, log));
    return rcpp_result_gen;
END_RCPP
}
// rWishart
arma::cube rWishart(int n, double df, const arma::mat& S);
RcppExport SEXP _ksm_rWishart(SEXP nSEXP, SEXP dfSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(rWishart(n, df, S));
    return rcpp_result_gen;
END_RCPP
}
// rinvWishart
arma::cube rinvWishart(int n, double df, const arma::mat& S);
RcppExport SEXP _ksm_rinvWishart(SEXP nSEXP, SEXP dfSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(rinvWishart(n, df, S));
    return rcpp_result_gen;
END_RCPP
}
// dsmnorm
arma::vec dsmnorm(const arma::cube& x, double b, const arma::mat& M, bool log);
RcppExport SEXP _ksm_dsmnorm(SEXP xSEXP, SEXP bSEXP, SEXP MSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dsmnorm(x, b, M, log));
    return rcpp_result_gen;
END_RCPP
}
// dsmnorm_mat
double dsmnorm_mat(const arma::mat& x, double b, const arma::mat& M, bool log);
RcppExport SEXP _ksm_dsmnorm_mat(SEXP xSEXP, SEXP bSEXP, SEXP MSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dsmnorm_mat(x, b, M, log));
    return rcpp_result_gen;
END_RCPP
}
// dsmlnorm
arma::vec dsmlnorm(const arma::cube& x, double b, const arma::mat& M, bool log);
RcppExport SEXP _ksm_dsmlnorm(SEXP xSEXP, SEXP bSEXP, SEXP MSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dsmlnorm(x, b, M, log));
    return rcpp_result_gen;
END_RCPP
}
// dmbeta2
arma::vec dmbeta2(const arma::cube& x, double shape1, double shape2, bool log);
RcppExport SEXP _ksm_dmbeta2(SEXP xSEXP, SEXP shape1SEXP, SEXP shape2SEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dmbeta2(x, shape1, shape2, log));
    return rcpp_result_gen;
END_RCPP
}
// rmbeta2
arma::cube rmbeta2(int n, int d, double shape1, double shape2);
RcppExport SEXP _ksm_rmbeta2(SEXP nSEXP, SEXP dSEXP, SEXP shape1SEXP, SEXP shape2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type shape1(shape1SEXP);
    Rcpp::traits::input_parameter< double >::type shape2(shape2SEXP);
    rcpp_result_gen = Rcpp::wrap(rmbeta2(n, d, shape1, shape2));
    return rcpp_result_gen;
END_RCPP
}
// solvericcati
Rcpp::List solvericcati(arma::mat M, arma::mat S, double tol, int maxiter);
RcppExport SEXP _ksm_solvericcati(SEXP MSEXP, SEXP SSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(solvericcati(M, S, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// dsmlnorm_mat
double dsmlnorm_mat(const arma::mat& x, const arma::mat& matlog_x, double b, const arma::mat& M, const arma::mat& matlog_M, bool log);
RcppExport SEXP _ksm_dsmlnorm_mat(SEXP xSEXP, SEXP matlog_xSEXP, SEXP bSEXP, SEXP MSEXP, SEXP matlog_MSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matlog_x(matlog_xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type matlog_M(matlog_MSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dsmlnorm_mat(x, matlog_x, b, M, matlog_M, log));
    return rcpp_result_gen;
END_RCPP
}
// lcvkernsmlnorm
double lcvkernsmlnorm(const arma::cube& x, const double& b, const int& h);
RcppExport SEXP _ksm_lcvkernsmlnorm(SEXP xSEXP, SEXP bSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(lcvkernsmlnorm(x, b, h));
    return rcpp_result_gen;
END_RCPP
}
// lcvkernsmnorm
double lcvkernsmnorm(const arma::cube& x, const double& b, const int& h);
RcppExport SEXP _ksm_lcvkernsmnorm(SEXP xSEXP, SEXP bSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(lcvkernsmnorm(x, b, h));
    return rcpp_result_gen;
END_RCPP
}
// lcvkernWishart
double lcvkernWishart(const arma::cube& x, const double& b, const double& h);
RcppExport SEXP _ksm_lcvkernWishart(SEXP xSEXP, SEXP bSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(lcvkernWishart(x, b, h));
    return rcpp_result_gen;
END_RCPP
}
// lcvsymmat
Rcpp::List lcvsymmat(const arma::cube& x, const arma::vec b, const int& h, std::string kernel);
RcppExport SEXP _ksm_lcvsymmat(SEXP xSEXP, SEXP bSEXP, SEXP hSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int& >::type h(hSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(lcvsymmat(x, b, h, kernel));
    return rcpp_result_gen;
END_RCPP
}
// kdensWishart
Rcpp::NumericVector kdensWishart(const arma::cube& x, const arma::cube& xs, const double& b, bool log);
RcppExport SEXP _ksm_kdensWishart(SEXP xSEXP, SEXP xsSEXP, SEXP bSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(kdensWishart(x, xs, b, log));
    return rcpp_result_gen;
END_RCPP
}
// kdenssmlnorm
Rcpp::NumericVector kdenssmlnorm(const arma::cube& x, const arma::cube& xs, double b, bool log);
RcppExport SEXP _ksm_kdenssmlnorm(SEXP xSEXP, SEXP xsSEXP, SEXP bSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(kdenssmlnorm(x, xs, b, log));
    return rcpp_result_gen;
END_RCPP
}
// kdenssmnorm
Rcpp::NumericVector kdenssmnorm(const arma::cube& x, const arma::cube& xs, double b, bool log);
RcppExport SEXP _ksm_kdenssmnorm(SEXP xSEXP, SEXP xsSEXP, SEXP bSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(kdenssmnorm(x, xs, b, log));
    return rcpp_result_gen;
END_RCPP
}
// kdens_symmat
Rcpp::NumericVector kdens_symmat(const arma::cube& x, const arma::cube& xs, std::string kernel, double b, bool log);
RcppExport SEXP _ksm_kdens_symmat(SEXP xSEXP, SEXP xsSEXP, SEXP kernelSEXP, SEXP bSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(kdens_symmat(x, xs, kernel, b, log));
    return rcpp_result_gen;
END_RCPP
}
// lscvkernwishart
double lscvkernwishart(const arma::cube& x, const double& b, const int& h);
RcppExport SEXP _ksm_lscvkernwishart(SEXP xSEXP, SEXP bSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(lscvkernwishart(x, b, h));
    return rcpp_result_gen;
END_RCPP
}
// lscvkernsmlnorm
double lscvkernsmlnorm(const arma::cube& x, const double& b, const int& h);
RcppExport SEXP _ksm_lscvkernsmlnorm(SEXP xSEXP, SEXP bSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(lscvkernsmlnorm(x, b, h));
    return rcpp_result_gen;
END_RCPP
}
// lscvsymmat
Rcpp::List lscvsymmat(const arma::cube& x, const arma::vec b, const int& h, std::string kernel);
RcppExport SEXP _ksm_lscvsymmat(SEXP xSEXP, SEXP bSEXP, SEXP hSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int& >::type h(hSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(lscvsymmat(x, b, h, kernel));
    return rcpp_result_gen;
END_RCPP
}
// rmnorm
Rcpp::NumericMatrix rmnorm(int n, const arma::vec& mean, const arma::mat& vcov);
RcppExport SEXP _ksm_rmnorm(SEXP nSEXP, SEXP meanSEXP, SEXP vcovSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vcov(vcovSEXP);
    rcpp_result_gen = Rcpp::wrap(rmnorm(n, mean, vcov));
    return rcpp_result_gen;
END_RCPP
}
// fdens
Rcpp::NumericVector fdens(const arma::cube& x, const int& model, const int& d);
RcppExport SEXP _ksm_fdens(SEXP xSEXP, SEXP modelSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const int& >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(fdens(x, model, d));
    return rcpp_result_gen;
END_RCPP
}
// rdens
arma::cube rdens(int n, const int& model, const int& d);
RcppExport SEXP _ksm_rdens(SEXP nSEXP, SEXP modelSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const int& >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(rdens(n, model, d));
    return rcpp_result_gen;
END_RCPP
}
// ise_montecarlo
Rcpp::NumericVector ise_montecarlo(const arma::cube& x, double b, std::string kernel, const int& model, int B, double delta);
RcppExport SEXP _ksm_ise_montecarlo(SEXP xSEXP, SEXP bSEXP, SEXP kernelSEXP, SEXP modelSEXP, SEXP BSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const int& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(ise_montecarlo(x, b, kernel, model, B, delta));
    return rcpp_result_gen;
END_RCPP
}
// kldiv_montecarlo
Rcpp::NumericVector kldiv_montecarlo(const arma::cube& x, double b, std::string kernel, const int& model, int B, int nrep);
RcppExport SEXP _ksm_kldiv_montecarlo(SEXP xSEXP, SEXP bSEXP, SEXP kernelSEXP, SEXP modelSEXP, SEXP BSEXP, SEXP nrepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const int& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    rcpp_result_gen = Rcpp::wrap(kldiv_montecarlo(x, b, kernel, model, B, nrep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ksm_symmetrize", (DL_FUNC) &_ksm_symmetrize, 1},
    {"_ksm_sumlog", (DL_FUNC) &_ksm_sumlog, 1},
    {"_ksm_meanlog", (DL_FUNC) &_ksm_meanlog, 1},
    {"_ksm_sumsignedlog", (DL_FUNC) &_ksm_sumsignedlog, 2},
    {"_ksm_rotation2d", (DL_FUNC) &_ksm_rotation2d, 1},
    {"_ksm_rotation3d", (DL_FUNC) &_ksm_rotation3d, 1},
    {"_ksm_rotation_scaling", (DL_FUNC) &_ksm_rotation_scaling, 2},
    {"_ksm_mgamma", (DL_FUNC) &_ksm_mgamma, 3},
    {"_ksm_lmgamma", (DL_FUNC) &_ksm_lmgamma, 2},
    {"_ksm_dWishart", (DL_FUNC) &_ksm_dWishart, 4},
    {"_ksm_dinvWishart", (DL_FUNC) &_ksm_dinvWishart, 4},
    {"_ksm_dWishart_mat", (DL_FUNC) &_ksm_dWishart_mat, 4},
    {"_ksm_rWishart", (DL_FUNC) &_ksm_rWishart, 3},
    {"_ksm_rinvWishart", (DL_FUNC) &_ksm_rinvWishart, 3},
    {"_ksm_dsmnorm", (DL_FUNC) &_ksm_dsmnorm, 4},
    {"_ksm_dsmnorm_mat", (DL_FUNC) &_ksm_dsmnorm_mat, 4},
    {"_ksm_dsmlnorm", (DL_FUNC) &_ksm_dsmlnorm, 4},
    {"_ksm_dmbeta2", (DL_FUNC) &_ksm_dmbeta2, 4},
    {"_ksm_rmbeta2", (DL_FUNC) &_ksm_rmbeta2, 4},
    {"_ksm_solvericcati", (DL_FUNC) &_ksm_solvericcati, 4},
    {"_ksm_dsmlnorm_mat", (DL_FUNC) &_ksm_dsmlnorm_mat, 6},
    {"_ksm_lcvkernsmlnorm", (DL_FUNC) &_ksm_lcvkernsmlnorm, 3},
    {"_ksm_lcvkernsmnorm", (DL_FUNC) &_ksm_lcvkernsmnorm, 3},
    {"_ksm_lcvkernWishart", (DL_FUNC) &_ksm_lcvkernWishart, 3},
    {"_ksm_lcvsymmat", (DL_FUNC) &_ksm_lcvsymmat, 4},
    {"_ksm_kdensWishart", (DL_FUNC) &_ksm_kdensWishart, 4},
    {"_ksm_kdenssmlnorm", (DL_FUNC) &_ksm_kdenssmlnorm, 4},
    {"_ksm_kdenssmnorm", (DL_FUNC) &_ksm_kdenssmnorm, 4},
    {"_ksm_kdens_symmat", (DL_FUNC) &_ksm_kdens_symmat, 5},
    {"_ksm_lscvkernwishart", (DL_FUNC) &_ksm_lscvkernwishart, 3},
    {"_ksm_lscvkernsmlnorm", (DL_FUNC) &_ksm_lscvkernsmlnorm, 3},
    {"_ksm_lscvsymmat", (DL_FUNC) &_ksm_lscvsymmat, 4},
    {"_ksm_rmnorm", (DL_FUNC) &_ksm_rmnorm, 3},
    {"_ksm_fdens", (DL_FUNC) &_ksm_fdens, 3},
    {"_ksm_rdens", (DL_FUNC) &_ksm_rdens, 3},
    {"_ksm_ise_montecarlo", (DL_FUNC) &_ksm_ise_montecarlo, 6},
    {"_ksm_kldiv_montecarlo", (DL_FUNC) &_ksm_kldiv_montecarlo, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ksm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
